// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: boards.sql

package db

import (
	"context"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (name, user_id)
VALUES ($1, $2)
RETURNING id, user_id, name, created_at, updated_at
`

type CreateBoardParams struct {
	Name   string
	UserID int32
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, createBoard, arg.Name, arg.UserID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBoards = `-- name: GetBoards :many
SELECT id, user_id, name, created_at, updated_at FROM boards
WHERE user_id = $1
`

func (q *Queries) GetBoards(ctx context.Context, userID int32) ([]Board, error) {
	rows, err := q.db.QueryContext(ctx, getBoards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Board
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
