// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Board struct {
	ID        int32
	UserID    int32
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Task struct {
	ID          int32
	UserID      int32
	Title       string
	Description sql.NullString
	Status      sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	BoardID     sql.NullInt32
}

type User struct {
	ID        int32
	Email     string
	Password  string
	CreatedAt sql.NullTime
}
