// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Board struct {
	ID        int32
	UserID    int32
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Task struct {
	ID          int32
	UserID      int32
	Title       string
	Description pgtype.Text
	Status      pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	BoardID     pgtype.Int4
}

type User struct {
	ID        int32
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
}
