// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (board_id, user_id, title, description, status, priority, deadline)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, title, description, status, priority, deadline, created_at, updated_at, board_id
`

type CreateTaskParams struct {
	BoardID     pgtype.Int4
	UserID      int32
	Title       string
	Description pgtype.Text
	Status      pgtype.Text
	Priority    string
	Deadline    pgtype.Timestamp
}

type CreateTaskRow struct {
	ID          int32
	UserID      int32
	Title       string
	Description pgtype.Text
	Status      pgtype.Text
	Priority    string
	Deadline    pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	BoardID     pgtype.Int4
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.BoardID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Deadline,
	)
	var i CreateTaskRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BoardID,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM tasks
WHERE id = $1 AND board_id = $2 AND user_id = $3
`

type DeleteTaskParams struct {
	ID      int32
	BoardID pgtype.Int4
	UserID  int32
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.BoardID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTasks = `-- name: GetTasks :many
SELECT 
  id, user_id, title, description, status, priority, deadline, created_at, updated_at, board_id
FROM tasks
WHERE board_id = $1
  AND (
    COALESCE($2::text, '') = '' OR
    title ILIKE '%' || $2::text || '%' OR
    description ILIKE '%' || $2::text || '%'
  )
  AND (
    COALESCE($3::text, '') = '' OR
    status = $3
  )
  AND (
    COALESCE($4::text, '') = '' OR
    priority = $4
  )
  AND (
    $5::bool = false
    OR (
      $5::bool = true AND
      (
        ($6::bool = true AND deadline IS NOT NULL)
        OR
        ($6::bool = false AND deadline IS NULL)
      )
    )
  )
ORDER BY
  CASE WHEN $7::int = 0 THEN created_at END DESC,
  CASE WHEN $7::int = 1 THEN created_at END ASC,
  CASE WHEN $7::int = 2 THEN deadline END ASC NULLS LAST,
  CASE WHEN $7::int = 3 THEN deadline END DESC NULLS LAST,
  created_at DESC
`

type GetTasksParams struct {
	BoardID        pgtype.Int4
	Search         string
	Status         string
	Priority       string
	HasDeadlineSet bool
	HasDeadline    bool
	SortCode       int32
}

type GetTasksRow struct {
	ID          int32
	UserID      int32
	Title       string
	Description pgtype.Text
	Status      pgtype.Text
	Priority    string
	Deadline    pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	BoardID     pgtype.Int4
}

func (q *Queries) GetTasks(ctx context.Context, arg GetTasksParams) ([]GetTasksRow, error) {
	rows, err := q.db.Query(ctx, getTasks,
		arg.BoardID,
		arg.Search,
		arg.Status,
		arg.Priority,
		arg.HasDeadlineSet,
		arg.HasDeadline,
		arg.SortCode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTasksRow
	for rows.Next() {
		var i GetTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Deadline,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BoardID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
    title = COALESCE($1, title),
    description = COALESCE($2, description),
    status = COALESCE($3, status),
    priority = COALESCE($4, priority),
    deadline = COALESCE($5, deadline),
    updated_at = now()
WHERE id = $6 AND board_id = $7 AND user_id = $8
RETURNING id, user_id, title, description, status, created_at, updated_at, board_id, priority, deadline
`

type UpdateTaskParams struct {
	Title       pgtype.Text
	Description pgtype.Text
	Status      pgtype.Text
	Priority    pgtype.Text
	Deadline    pgtype.Timestamp
	ID          int32
	BoardID     pgtype.Int4
	UserID      int32
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Deadline,
		arg.ID,
		arg.BoardID,
		arg.UserID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BoardID,
		&i.Priority,
		&i.Deadline,
	)
	return i, err
}
